### PR TITLE
fix #103 more performant time remaining

### LINKED ISSUE #103: Channel filter not subtracted from characters remaining.
When in a tabbed channel, the input field does not account for the channel filter, and therefore using all 140 characters results in the error: '[robin] could not send your message'.

### PR DESCRIPTION
**Pull request by vinnymac**
@Daegalus @dashed 

We were discussing a more performant version of the text counter updating last night. I had an r/showerthoughts moment today and got it working.

### CODE REVIEW

**Comment by ghost** [comment]
Nice work. I think Backbone.\* could solve other issues too.

**Comment by ghost** [comment]
This had to be reverted (broke Parrot for some people). Please rework.

**Comment by vinnymac** [comment]
Interesting, I will investigate.

EDIT: It should be related to the trigger if anything. I haven't been able to reproduce the issue, so I will need steps to reproduce in order to build a proper fix.

EDIT 2: Users were reporting this was completely breaking the script for them, while this was working fine for other users (including myself). We don't use Backbone elsewhere so perhaps that is related.

**Comment by ghost** [comment]
Does this call an external script? This broke parrot for me in Firefox + Grease Monkey + uBlock Origin + uMatrix. It's possible need to whitelist an external script to unbreak it?

**Comment by vinnymac** [comment]
@aqueueentrappedthemouth by external do you mean on a different domain than reddits cdn or do you mean outside of our script we've built here?

This code refers to `Backbone` which is globally available on the window object when you visit reddit. If it is related to that, then I think I have some ideas on how I might fix it. Let me gives grease monkey and firefox a try and see what happens.

EDIT: Yep, that confirms it. Firefox with Greasemonkey did it. It looks like referencing anything on the window breaks it. So since I am referring to window.r and window.Backbone it fails. I guess tampermonkey is letting those variables exist on the window while greasemonkey is not. It is a shame that is happening, I haven't seen this behavior with other scripts I worked on.

**Pull request merged**
