### PR TITLE
Fix hasChannel again.

### PR DESCRIPTION
**Pull request by daegalus**
Somehow my change got reverted, so I fixed it. THis is the before and after:

Before: http://i.imgur.com/h90pdWx.png
After: http://i.imgur.com/yfTuXNf.png

### CODE REVIEW

**Comment by 5a1t** [comment]
Thanks! Must have gotten messed up in a merge.

**Comment by dashed** [comment]
nah this was intentional change i did locking down a certain subtle bug.

**Comment by 5a1t** [comment]
Oh, should we revert?

**Comment by dashed** [comment]
yep.

**Comment by 5a1t** [comment]
Reverted - what is the bug dashed?  Think we can remerge this after, or are you taking a new approach?

**Pull request merged**
