### PR TITLE
Migrate standings view to parrot.

### PR DESCRIPTION
**Pull request by mootinator**
Rebase standings viewer (reads from Reddit) on parrot.

Closed:
image

Open:
image

### CODE REVIEW

**Comment by mootinator** [comment]
Don't hate me because I'm a dirty stayer.

**Comment by 5a1t** [comment]
Potential code injection, testing.

**Comment by 5a1t** [comment]
I do like it though :+1:

**Comment by 5a1t** [comment]
I think it's safe - rss feed is cleaned by reddit.  Worst attack would still require link click.

**Pull request merged**
