### PR TITLE
Turned the chat messages into table view (using mostly CSS)

### PR DESCRIPTION
**Pull request by ghost**
It should look a lot better now with text nicely aligned! Also word-breaks should be disabled (I think).

### CODE REVIEW

**Comment by dashed** [comment]
hmm the timestamps get squished.

**Comment by ghost** [comment]
Hmm, it looks correct to me. But I added a nowrap to the time and the username column now so it should never wrap now, hopefully.

**Comment by dashed** [comment]
@notmythriz LGTM! thanks!

**Comment by dashed** [comment]
reverting as it seems to cause problems for some.

**Pull request merged**
