### PR TITLE
user selectable irc-client like formatting (xchat/mirc)

### PR DESCRIPTION
**Pull request by Annon201**
Different formatting styles, now with more pointy brackets.

### CODE REVIEW

**Comment by Annon201** [comment]
https://imgur.com/2nPOPBu.png

**Comment by dashed** [comment]
Hey thanks @Annon201 . Are you in "soKukunelitsWoGtdiwenasmkkakmanianalind..." chat  by any chance?

**Comment by dashed** [comment]
Annon201 if u fix up your script it may be merged :)

**Comment by daegalus** [comment]
I looked at the screenshot, it seems most of this is taken care of with my changes I made, except for the ability to turn it on/off.

We can close this, and just work on a formatting on/off button? not sure. This will revert a lot of my changes.

**Pull request closed without merging**
