### PR TITLE
Add setting for sent message history.

### PR DESCRIPTION
**Pull request by LTAcosta**

### CODE REVIEW

**Comment by dashed** [comment]
@LTAcosta ah. i already did this. Your feature is  out in the wild on v2.69

**Comment by LTAcosta** [comment]
Oh, haha. Nevermind then. I thought your previous comment was asking me to do it, lol.

**Comment by LTAcosta** [comment]
Well there, now this just resolves some of our minor differences, such as the while loop when reducing the size.

**Comment by dashed** [comment]
Cool. Thanks @LTAcosta ! :+1:

**Pull request merged**
